name = "RestrainJIT"
uuid = "fd75267b-706d-47c7-94dc-0cf3abf02ef7"
authors = ["thautwarm"]
version = "0.1.0"

[deps]
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
